- .gitignore
- README.md
- requests_builder.py
- variable_parser.py
Enable use of variables in the api.yaml
> Enable use of variables in the api.yaml

- README.md
- requests_builder.py
- variable_parser.py
> Chaining Requests

- docs_writer.py
- requests_builder.py
> Nested endpoints

- README.md
- scanapi/requests_builder.py
Add query params to requests and updated README with params example.
Closes https://github.com/camilamaia/scanapi/issues/4
> Add query params

- README.md
- scanapi/docs_writer.py
- scanapi/requests_builder.py
Add post requests.
Corrected bytes to json conversion in request writer.
Closes https://github.com/camilamaia/scanapi/issues/5
> Add post requests

- CONTRIBUTING.md
- README.md
> Improve contributting docs

- scanapi/__init__.py
- scanapi/api_node.py
- scanapi/requests_builder.py
- scanapi/variable_parser.py
- setup.py
Refactor: Using nodes to handle iterations
> Refactor: Using nodes to handle iterations

- .gitignore
- README.md
- examples/cat_api/.scanapi.yaml
- examples/cat_api/api.yaml
- examples/cat_api/docs.md
- examples/json_place_holder/.scanapi.yaml
- examples/json_place_holder/api.yaml
- examples/json_place_holder/docs.md
- examples/open_weather_map/.scanapi.yaml
- examples/open_weather_map/api.yaml
- examples/open_weather_map/docs.md
- scanapi/__init__.py
- scanapi/api_node.py
- scanapi/requests_builder.py
- scanapi/variable_parser.py
- setup.py
Add examples:
- [The Cat API](https://thecatapi.com)
- [JSONPlaceholder](https://jsonplaceholder.typicode.com)
- [OpenWeatherMap](http://openweathermap.org/)
And minor fixes on README
For now, examples are also being used for test purposes. We pray for a world with unit tests 🙏 Next task 😉 🚀
> Add examples and minor fixes on README

- README.md
- scanapi/__init__.py
- scanapi/api_node.py
- scanapi/requests_builder.py
- scanapi/variable_parser.py
- tests/functional/step_defs/test_call_requests.py
> Refactor: build and call requests

- README.md
- examples/json_place_holder/api.yaml
- examples/json_place_holder/docs.md
- scanapi/api_node.py
- scanapi/requests_builder.py
- tests/data/specs/with_endpoints/minimal_get.yaml
- tests/data/specs/without_endpoints/minimal_get.yaml
- tests/unit/test_request_builder.py
closes https://github.com/camilamaia/scanapi/issues/6
> PUT HTTP method

- README.md
- scanapi/__init__.py
- scanapi/docs_writer.py
- scanapi/errors.py
- scanapi/requests_builder.py
- scanapi/yaml_loader.py
```bash
$ scanapi --help
Usage: scanapi [OPTIONS]
Automated Testing and Documentation for your REST API.
Options:
-s, --spec-path PATH
-d, --docs-path TEXT
--log-level [DEBUG|INFO|WARNING|ERROR|CRITICAL]
--help                          Show this message and exit.
```
Closes https://github.com/camilamaia/scanapi/issues/25
> Add logging

- scanapi/api_node.py
- scanapi/requests_builder.py
- scanapi/variable_parser.py
Fix vars interpolation and redirect
> Fix vars interpolation and redirect

- setup.py
> Bump version 0.0.10

- Dockerfile
- setup.py
> Bump version 0.0.11 and Dockerfile

- scanapi/errors.py
- scanapi/requests_builder.py
- scanapi/variable_parser.py
- tests/data/specs/with_endpoints/get_with_root_requests.yaml
- tests/unit/test_request_builder.py
- tests/unit/test_variable_parser.py
> Test variable parser

- .circleci/config.yml
- README.md
Just a simple config. We can include other things on top of this later.
I think you need to configure the project on CircleCI first, but the expected output of the build should be something like this:
https://app.circleci.com/jobs/github/barbosa/scanapi/9
closes #35
> circleci: initial config

- scanapi/variable_parser.py
Using raw strings and named groups for regex
> Using raw strings and named groups for regex

- scanapi/__init__.py
- scanapi/docs_writer.py
- scanapi/tree/request_node.py
- scanapi/yaml_loader.py
> Refactor: Remove format()

- tests/data/specs/with_endpoints/get_with_header_body_params.yaml
- tests/unit/factories.py
- tests/unit/test_request_maker.py
Increasing coverage
Related with https://github.com/camilamaia/scanapi/issues/14
> Increasing coverage

- scanapi/tree/endpoint_node.py
- tests/unit/tree/test_endpoint_node.py
Before
```
url_1 = "http://demo.scanapi.dev/api/"
url_2 = "/health/"
join => "http://demo.scanapi.dev/api/health"
```
After
```
url_1 = "http://demo.scanapi.dev/api/"
url_2 = "/health/"
join => "http://demo.scanapi.dev/api/health/"
```
> Fix join of urls and add tests for it

- CONTRIBUTING.md
Add `Bump lib Version` step to Deploy instructions
> Add `Bump lib Version` step to Deploy instructions

- README.md
Change relative path to full url
> Fix broken link to CONTRIBUTING.md file on PyPi

- setup.py
#@ Description
Fix error when running scanapi
```
from scanapi.tree.api_tree import APITree
ModuleNotFoundError: No module named 'scanapi.tree'
```
Closes https://github.com/camilamaia/scanapi/issues/82
> Added missing init files

- CHANGELOG.md
Used [Release notes](https://github.com/camilamaia/scanapi/releases) & [keepachangelog.com](https://keepachangelog.com/en/1.0.0/) reference.
> add as per issue #88

- .circleci/config.yml
Add black check to CircleCI pipeline
Closes #91
> Add black check to CircleCI pipeline

- .circleci/config.yml
- CHANGELOG.md
Add changelog-linter to CircleCI pipeline
Closes #89
> Add changelog-linter to CircleCI pipeline

- CHANGELOG.md
- setup.py
- Return params/headers None when request doesn't have params/headers #87
- Report-example image not loading on PyPi #86
> [Release] v0.0.18

- README.md
Remove title from README.md since we already have image header.
> Remove title from README.md

- README.md
> Fix CircleCI badge

- CHANGELOG.md
- README.md
- scanapi/requests_maker.py
- tests/unit/test_request_maker.py
> Add patch http method

- CONTRIBUTING.md
Add `Upgrade ScanAPI on ScanAPI Demo` to deploy section on CONTRIBUTING.md
> Add Update ScanAPI Demo to deploy section

- .gitignore
- CHANGELOG.md
- scanapi/templates/markdown.jinja
The current state can be seen at the comment below.
fixes #60
> reporter: beautify markdown reporter

- scanapi/templates/console.jinja
- scanapi/templates/html.jinja
- scanapi/templates/markdown.jinja
Fix extra lines on templates and add missing http methods for html and console templates
| Header    | Value       |
|-----------|-------------|
| User-Agent | python-requests/2.23.0 |
| Accept-Encoding | gzip, deflate |
| Accept | */* |
| Connection | keep-alive |
| Content-Length | 2 |
| Content-Type | application/json |
| Header    | Value       |
|-----------|-------------|
| User-Agent | python-requests/2.23.0 |
| Accept-Encoding | gzip, deflate |
| Accept | */* |
| Connection | keep-alive |
| Content-Length | 2 |
| Content-Type | application/json |
```
ScanAPI Report: Console
=======================
http://demo.scanapi.dev/api/health/ - 200
http://demo.scanapi.dev/api/languages/ - 200
http://demo.scanapi.dev/api/devs/ - 200
http://demo.scanapi.dev/api/devs/?newOpportunities=True - …
```
> Fix extra lines on templates and add missing http methods

- README.md
- scanapi/reporter.py
- scanapi/templates/markdown.jinja
- setup.py
You can find how the report is going to be rendered In the comment bellow 👇 
Closes https://github.com/scanapi/scanapi/issues/26
> Improve Markdown Template

- scanapi/__init__.py
- scanapi/config_loader.py
- scanapi/errors.py
- scanapi/settings.py
- tests/unit/test_config_loader.py
Make yaml_loader more generic - config_loader, because we can also have config files as JSON.
> Make yaml_loader more generic

- CHANGELOG.md
- README.md
- scanapi/__init__.py
- scanapi/reporter.py
- scanapi/settings.py
- scanapi/utils.py
- tests/unit/test_settings.py
- tests/unit/test_utils.py
Closes https://github.com/scanapi/scanapi/issues/122
Closes https://github.com/scanapi/scanapi/issues/123
> Refactor: settings

- .github/workflows/changelog.yml
- CHANGELOG.md
We may be able to test only on future PRs though.
Closes #94
> actions: include workflow checking from missing changelog

- scanapi/__init__.py
Removed warning of custom template not implemented. Feature implemente on PR #126
> Remove warning of custom template not implemented

- CHANGELOG.md
- setup.py
- Automated pypi deploy - [#144](https://github.com/scanapi/scanapi/pull/144)
> Release v0.1.0

- scanapi/errors.py
- scanapi/tree/endpoint_node.py
- scanapi/tree/request_node.py
- scanapi/utils.py
- tests/unit/evaluators/test_spec_evaluator.py
- tests/unit/tree/test_endpoint_node.py
- tests/unit/tree/test_request_node.py
Adds required keys to request and endpoint nodes.
> Adds validation for required keys in endpoint and request nodes

- CONTRIBUTING.md
- README.md
> Add more instructions to CONTRIBUTING and update README with examples

- CHANGELOG.md
- README.md
> readme: update hero and center badges

- CHANGELOG.md
- README.md
- scanapi/main.py
- scanapi/reporter.py
- scanapi/templates/console.jinja
- tests/unit/test_reporter.py
> Remove Console Report

- CHANGELOG.md
- scanapi/session.py
- scanapi/templates/html.jinja
- tests/unit/test_session.py
Improve render of test results on report
> Improve html report

- CHANGELOG.md
- scanapi/errors.py
- scanapi/evaluators/code_evaluator.py
- scanapi/evaluators/string_evaluator.py
- scanapi/exit_code.py
- scanapi/scan.py
- scanapi/session.py
- scanapi/templates/html.jinja
- scanapi/test_status.py
- scanapi/tree/endpoint_node.py
- scanapi/tree/request_node.py
- scanapi/tree/testing_node.py
- tests/unit/evaluators/test_code_evaluator.py
- tests/unit/test_main.py
- tests/unit/test_scan.py
- tests/unit/test_session.py
- tests/unit/tree/test_request_node.py
- tests/unit/tree/test_testing_node.py
- Handle properly exit errors 
- Add test errors to the report
- Improve Error Message for Invalid Python code error
Closes https://github.com/scanapi/scanapi/issues/104
Closes https://github.com/scanapi/scanapi/issues/105
Closes https://github.com/scanapi/scanapi/issues/106
> Handle properly exit errors and add test erros on report

- CHANGELOG.md
- README.md
- scanapi/main.py
Closes https://github.com/scanapi/scanapi/issues/130
> Add CLI options explanation

- CHANGELOG.md
- README.md
Fix report example images not loading on PyPI
> Fix report example images not loading on PyPI

- CHANGELOG.md
- setup.py
- Report example images not loading on PyPI [#193](https://github.com/scanapi/scanapi/pull/193)
> Release v1.0.1

- CHANGELOG.md
- setup.py
Fix for issue https://github.com/scanapi/scanapi/issues/196
Reference: https://stackoverflow.com/questions/7522250/how-to-include-package-data-with-setuptools-distribute
> Fix for TemplateNotFound

- CHANGELOG.md
- setup.py
- Fix for TemplateNotFound Error [#197](https://github.com/scanapi/scanapi/pull/197)
> Release v1.0.2

- CHANGELOG.md
- setup.py
> Release v1.0.3

- .github/workflows/pytest-and-codecov.yml
- CONTRIBUTING.md
- Makefile
- poetry.lock
- pyproject.toml
Now, we can run the `test` ussing `Makefile`
Close #44
> Run tests with makefile and install black dependency

- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- pyproject.toml
README.md
- English grammar and readability fixes.
CONTRIBUTING.md
- Change `versions` link to point to a public link.
- English grammar and readability fixes.
> Minor textual review of text files in the repo.

- .github/CODEOWNERS
Add github codeowners
Closes #232
> Add github codeowners

- README.md
> Add spectrum badge

- .github/workflows/publish-to-pypi.yml
- CHANGELOG.md
Issue https://github.com/scanapi/scanapi/issues/146
> feat: Add workflow to package/publish to test PyPi

- CHANGELOG.md
- scanapi/__init__.py
- scanapi/__main__.py
- tests/unit/test_main.py
- [BREAKING] - Changed command `scanapi <spec_file>` to `scanapi run <spec_file>`.
> Change command "scanapi <spec_file>" to "scanapi run <spec_file>"

- CHANGELOG.md
- scanapi/templates/report.html
Fixes #233 
Fixes #248 
Firefox:
Chrome:
> Fix css issues with html template

- CONTRIBUTING.md
- Dockerfile
- pyproject.toml
Add instructions to update Dockerfile on deploy
> Add instructions to update Dockerfile on deploy

- .github/actions/black/Dockerfile
- .github/actions/black/entrypoint.sh
- .github/workflows/lint.yml
- README.md
- pyproject.toml
Add newcomers guide reference to README.md
> Add newcomers guide reference to README.md

- CHANGELOG.md
- pyproject.toml
- scanapi/reporter.py
> Show absolute path to the report in CLI

- .github/workflows/run-examples.yml
- pyproject.toml
Runs ScanAPI examples on every pull request to ensure the new changes will not break the lib.
Closes https://github.com/scanapi/scanapi/issues/153
> Run examples on github workflow

- CHANGELOG.md
- pyproject.toml
- scanapi/evaluators/string_evaluator.py
- tests/unit/evaluators/test_string_evaluator.py
Considering dash in variable names
Closes #279
> Considering dash in variable names

- .pre-commit-config.yaml
- poetry.lock
- pyproject.toml
- scanapi/__main__.py
- scanapi/config_loader.py
- scanapi/evaluators/code_evaluator.py
- scanapi/evaluators/spec_evaluator.py
- scanapi/reporter.py
- scanapi/scan.py
- scanapi/session.py
- scanapi/settings.py
- scanapi/template_render.py
- scanapi/tree/endpoint_node.py
- scanapi/tree/request_node.py
- scanapi/tree/testing_node.py
- tests/unit/evaluators/test_code_evaluator.py
- tests/unit/evaluators/test_spec_evaluator.py
- tests/unit/evaluators/test_string_evaluator.py
- tests/unit/test_config_loader.py
- tests/unit/test_hide_utils.py
- tests/unit/test_main.py
- tests/unit/test_reporter.py
- tests/unit/test_scan.py
- tests/unit/test_session.py
- tests/unit/test_settings.py
- tests/unit/test_template_render.py
- tests/unit/test_utils.py
- tests/unit/tree/test_endpoint_node.py
- tests/unit/tree/test_testing_node.py
Add isort and apply it
Closes https://github.com/scanapi/scanapi/issues/270
> Add isort and apply it

- poetry.lock
- pyproject.toml
- pytest.ini
This was done,  according issue #276
> move serttings of pytest to pyproject.toml

- CHANGELOG.md
- pyproject.toml
> Moved bandit to dev in pyproject.toml 

- .github/workflows/first-interaction.yml
- CHANGELOG.md
- pyproject.toml
> Add github action worflow for first-time contributor

- Makefile
- pyproject.toml
> .fix: Invalid value for '-l'

- CHANGELOG.md
- pyproject.toml
- scanapi/templates/report.html
New feature added to report.html
> Add copy snippet button to report (#263)

- CHANGELOG.md
- pyproject.toml
- scanapi/evaluators/string_evaluator.py
- tests/unit/test_template_render.py
> Removed unused imports

- .github/workflows/publish-to-pypi.yml
- .github/workflows/publish-to-test-pypi.yml
- CHANGELOG.md
> Updated poetry-publish version

- CHANGELOG.md
- scanapi/__main__.py
- scanapi/reporter.py
- scanapi/scan.py
- scanapi/settings.py
- tests/unit/test_main.py
- tests/unit/test_reporter.py
- tests/unit/test_scan.py
- tests/unit/test_settings.py
> --no-report flag

- CHANGELOG.md
- scanapi/__init__.py
- scanapi/__main__.py
- scanapi/evaluators/code_evaluator.py
- scanapi/scan.py
- scanapi/tree/request_node.py
- scanapi/tree/testing_node.py
- scanapi/utils.py
- tests/unit/evaluators/test_code_evaluator.py
- tests/unit/evaluators/test_spec_evaluator.py
- tests/unit/test_config_loader.py
- tests/unit/test_hide_utils.py
- tests/unit/test_main.py
- tests/unit/test_reporter.py
- tests/unit/test_scan.py
- tests/unit/test_settings.py
- tests/unit/test_utils.py
- tests/unit/tree/test_endpoint_node.py
- tests/unit/tree/test_request_node.py
- tests/unit/tree/test_testing_node.py
> Fixed all flake8 errors

- .gitignore
> Remove `scanapi-report.html' and 'scanapi.yaml' from gitignore

- .github/workflows/publish-to-test-pypi.yml
- .github/workflows/run-examples.yml
Closes https://github.com/scanapi/scanapi/issues/335
> Replace deprecated poetry setup gh action

- .pre-commit-config.yaml
- CHANGELOG.md
- poetry.lock
- pyproject.toml
- scanapi/template_render.py
- scanapi/templates/report.html
currently the curl command shown in the html does not work. It would be easy to fix by passing the `--compressed` flag. But I decided to make some modifications for future `httpx` support.
Closes: https://github.com/scanapi/scanapi/issues/332
> fix curl command

- .github/workflows/lint.yml
- CHANGELOG.md
- scanapi/__main__.py
- scanapi/errors.py
- scanapi/evaluators/spec_evaluator.py
- scanapi/hide_utils.py
- scanapi/settings.py
- scanapi/tree/endpoint_node.py
- scanapi/tree/request_node.py
- tests/unit/evaluators/test_code_evaluator.py
- tests/unit/evaluators/test_spec_evaluator.py
- tests/unit/evaluators/test_string_evaluator.py
- tests/unit/test_config_loader.py
- tests/unit/test_hide_utils.py
- tests/unit/test_main.py
- tests/unit/test_reporter.py
- tests/unit/test_scan.py
- tests/unit/test_settings.py
- tests/unit/test_template_render.py
- tests/unit/test_utils.py
- tests/unit/tree/test_endpoint_node.py
- tests/unit/tree/test_request_node.py
- tests/unit/tree/test_testing_node.py
.fix black in github ci and format files 
Close #342
> fix black and format files

- .github/workflows/lint.yml
- poetry.lock
- pyproject.toml
- tests/unit/test_scan.py
To improve the readability of the tests I created this pr by implementing `pytest-it`.
I'll put an image here:
The cool thing would be to use `pytest-it `in all test cases.
#339
> implement pytest-it to describe tests

- .flake8
- .github/actions/black/Dockerfile
- .github/actions/black/entrypoint.sh
- .github/workflows/lint.yml
- .pre-commit-config.yaml
- CHANGELOG.md
- Makefile
- poetry.lock
- pyproject.toml
Closes https://github.com/scanapi/scanapi/issues/351
> run black from makefile

- .github/workflows/publish-to-test-pypi.yml
Upgrade JRubics/poetry-publish to version 1.5
Related to #356
> Upgrade JRubics/poetry-publish

- .github/workflows/publish-to-pypi.yml
- .github/workflows/publish-to-test-pypi.yml
Upgrade JRubics/poetry-publish to v1.6
> Upgrade JRubics/poetry-publish to v1.6

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
Add CODE_OF_CONDUCT.md.
Closes #365
> Add CODE_OF_CONDUCT.md

- .github/workflows/run-examples.yml
> Fix github action "Run ScanAPI for Demo API"

- CHANGELOG.md
- scanapi/__main__.py
> Added --version command to return current scanapi version (#369)

- README.md
> Remove Spectrum Badge from README.md

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/how_to_question.md
* Added three templates for bug_report, feature_request and how to
question.
Closes https://github.com/scanapi/scanapi/issues/382
> Add issue template

- .deepsource.toml
* Added `.deepsource.toml` file to configure deepsource
Closes: https://github.com/scanapi/scanapi/issues/394
Adds code quality tool to help manage PR and increase code quality.
Adding a code quality tool will increase the overall code quality of the project.
Feature
Closes 394
> Add code quality tool

- scanapi/evaluators/code_evaluator.py
- scanapi/exit_code.py
- scanapi/hide_utils.py
- scanapi/reporter.py
- scanapi/scan.py
- scanapi/session.py
- scanapi/settings.py
- scanapi/template_render.py
- scanapi/tree/request_node.py
- scanapi/utils.py
Docstring line lengths are recommended to be no greater than 79 characters.
There are 32 occurrences of this issue in the repository.
See all occurrences on DeepSource &rarr; [deepsource.io/gh/scanapi/scanapi/issue/FLK-W505/occurrences/](https://deepsource.io/gh/scanapi/scanapi/issue/FLK-W505/occurrences/)
Fix deepsource issues
Fix
Closes #416
> Fix: Doc line too long FLK-W505

- CHANGELOG.md
- scanapi/evaluators/spec_evaluator.py
- scanapi/tree/endpoint_node.py
- scanapi/tree/request_node.py
- tests/unit/evaluators/test_code_evaluator.py
- tests/unit/evaluators/test_spec_evaluator.py
- tests/unit/tree/endpoint_node/test_validate.py
> Add 'vars' key to endpoint node

- CHANGELOG.md
- scanapi/__main__.py
- scanapi/reporter.py
- scanapi/scan.py
- scanapi/settings.py
- tests/unit/test_main.py
- tests/unit/test_reporter.py
- tests/unit/test_scan.py
- tests/unit/test_settings.py
Add --no-report flag
Adds feature from [this](https://github.com/scanapi/scanapi/issues/268) issue
Feature
- [Y]  I have added a changelog entry / my PR does not need a new changelog entry. [Instructions](https://github.com/scanapi/scanapi/wiki/Changelog).
- [Y] I have added/updated unit tests. [Instructions](https://github.com/scanapi/scanapi/wiki/Writing-Tests).
- [Y] New and existing unit tests pass locally with my changes. [Instructions](https://github.com/scanapi/scanapi/wiki/Run-ScanAPI-Locally#tests)
- [Y] I have self-documented code my changes by adding docstring(s) and comment(s). [Instructions](https://github.com/scanapi/scanapi/wiki/First-Pull-Request#7-make-your-changes)
- [Y] Current PR does not significantly decrease the code coverage and docstring coverage.
- [Y] My code …
> Add --no-report flag

- CHANGELOG.md
- Dockerfile
- pyproject.toml
- Enable 'vars' key at endpoint node. [#328](https://github.com/scanapi/scanapi/pull/328)
- Add `--no-report` flag. [#325](https://github.com/scanapi/scanapi/pull/325)
> Release v2.5.0

- scanapi/reporter.py
- scanapi/template_render.py
Fixed two anti-pattern issues from #403 
Because Deepsource said so, I guess
Couple of lines, simple stuff
Doesn't close #403, but checks off two changes of the list.
> Fix anti-pattern issues

- .github/CODEOWNERS
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/how_to_question.md
- .github/pull_request_template.md
Fix issue templates labels
Labels are not being applied when creating feature/bug/how-to issues. This started happening after we renamed the labels - capitalizing the words
Fix
Closes #473
> Fix issue templates labels

- scanapi/evaluators/code_evaluator.py
Updating docstring for code evaluator. 
Related to #441
code documentation
Closes #441
> Adds missing docstrings to `code_evaluator.py`

- tests/unit/tree/endpoint_node/test_get_specs.py
- tests/unit/tree/endpoint_node/test_run.py
This pull request adds unit tests for [test_get_specs.py](https://github.com/scanapi/scanapi/blob/main/tests/unit/tree/endpoint_node/test_get_specs.py) and [test_run.py](https://github.com/scanapi/scanapi/blob/main/tests/unit/tree/endpoint_node/test_run.py).
Issue #433 
Unit tests
Closes #433
> test: endpoint node methods

- .github/pull_request_template.md
Updates Pull Request Template with `I have squashed my commits` item in the checklist
Closes #451
> Updates Pull Request Template

- .github/workflows/first-interaction.yml
first-interaction action is not working and the fact we renamed all the labels to have the initial letter capitalized might be the root of the problem
https://github.com/scanapi/scanapi/issues/430
Bug fix
Might Closes https://github.com/scanapi/scanapi/issues/430
> fix: capitalize pr-label on first-interaction action

- .gitlint
- .pre-commit-config.yaml
- Makefile
- poetry.lock
- pyproject.toml
- scanapi/config_loader.py
Added a pre-commit hook to check if follow the conventional commits.
QA
Check if commit message follow the conventional commits.
Closes #438
> feat: add pre-commit hook to check if follow conventional commits (#438)

- scanapi/errors.py
- scanapi/settings.py
Change from (wrong) Py2 super() call to the simple Py3 form.
Also changing *all* super calls to the simpler form.
Local tests pass.
closes #455
> Use Python3 simple super call (close #455)

- tests/unit/evaluators/test_spec_evaluator.py
Add unit tests for method `__repr__` of `SpecEvaluator` class
Closes issue #486 
Unit testing
Closes #486
> test: add test for '__repr__' in SpecEvaluator

- scanapi/evaluators/string_evaluator.py
Updates docstrings for StringEvaluator class.
Related to #443 
Code documentation
Closes #443
> adds missing docstrings to ```string_evaluator.py```

- scanapi/__main__.py
- scanapi/errors.py
- scanapi/tree/endpoint_node.py
- scanapi/tree/request_node.py
- tests/unit/tree/endpoint_node/test_run.py
- tests/unit/tree/request_node/test_body.py
- tests/unit/tree/request_node/test_full_path_url.py
- tests/unit/tree/request_node/test_headers.py
- tests/unit/tree/request_node/test_params.py
Fix deep source issues:
- empty file
- unnecessary pass statement
- too general exception
- wrong import
Fix pipeline
#530
> [530] Fix deepsource issues

- .github/workflows/publish-to-pypi.yml
- .github/workflows/publish-to-test-pypi.yml
Fix GitHub action -> publish on test pypi 
Fix Github action -> publish to production
Pipeline is broken 
Closes #530
> fix: upgrade poetry/publish on test pypi github action

- .gitlint
ignore gitlint rules on release, squash and revert
> style: ignore gitlint rules on release, squash and revert

- scanapi/tree/request_node.py
Added commits from @leonardomaier 
#445 
Documentation
Closes #445
> docs: add docstring for Request Node class

- scanapi/console.py
- scanapi/scan.py
- scanapi/tree/request_node.py
- tests/unit/test_console.py
- tests/unit/test_scan.py
- tests/unit/tree/request_node/test_run.py
Fix https://github.com/scanapi/scanapi/issues/544
Bug
Closes #544
> fix: report is not printing the test cases

- CHANGELOG.md
- Dockerfile
- pyproject.toml
- Print test results summary in console [#497](https://github.com/scanapi/scanapi/issues/497)
- Error when using list (or any other) comprehension in Python Code [#515](https://github.com/scanapi/scanapi/pull/515)
> Release v2.6.2

- CHANGELOG.md
- Dockerfile
- pyproject.toml
- Implement new key `options` to request and endpoint nodes [#529](https://github.com/scanapi/scanapi/pull/552)
> Release v2.8.0

- .github/workflows/lint.yml
- .github/workflows/publish-to-production.yml
- .github/workflows/publish-to-test-pypi.yml
- .github/workflows/pytest-and-codecov.yml
- .github/workflows/run-examples.yml
> fix: poetry setup on workflows

- .github/workflows/pytest-and-codecov.yml
- Makefile
Fixes this: https://github.com/scanapi/scanapi/actions/runs/4290171692
> ci: update pytest-and-codecov.yml workflow

- CHANGELOG.md
- Dockerfile
- pyproject.toml
- Content field not rendered properly on Chrome [#551](https://github.com/scanapi/scanapi/issues/551)
> Release v2.8.2

- CHANGELOG.md
- Dockerfile
- pyproject.toml
- Enable the use of different content types [#521](https://github.com/scanapi/scanapi/issues/521)
- python -m scanapi command [#501](https://github.com/scanapi/scanapi/issues/501)
> Release v2.9.0

- .github/workflows/run-examples.yml
> ci: enable pull_request_target for examples workflow

- CHANGELOG.md
- pyproject.toml
> chore(deps): update click version

- CHANGELOG.md
- Dockerfile
- pyproject.toml
- Upgrade Click dependency [681](https://github.com/scanapi/scanapi/pull/681)
> Release v2.10.1

- CHANGELOG.md
- Dockerfile
- pyproject.toml
- Gitlint dev dependency [685](https://github.com/scanapi/scanapi/pull/685)
> Release v2.10.2

- Makefile
Adjusting `make install`
releated #683 
Bug Fix
Closes #683
> Adjusting `make install`

- .github/workflows/validate-pr-title-v1.yml
> ci: add validate-pr-title-v1.yml
