README.md
scanapi/docs_writer.py

Hide authorization info in the generated doc to avoid expose sensitive information.
Only working for headers now.
https://github.com/camilamaia/scanapi/issues/31

Hide Authorization

---

README.md
examples/cat_api/.env-sample
examples/cat_api/.scanapi.yaml
examples/json_place_holder/.env-sample
examples/open_weather_map/.scanapi.yaml
scanapi/errors.py
scanapi/variable_parser.py
setup.py
tests/functional/step_defs/test_call_requests.py

Stop declaring the env vars on `scanapi.yaml` file and start getting these variables in fact from the os.
Closes https://github.com/camilamaia/scanapi/issues/42

Using env variables from os

---

scanapi/reporter.py
scanapi/templates/markdown.jinja
setup.py
tests/unit/factories.py
tests/unit/test_reporter.py

Fix hiding sensitive info for headers, issue https://github.com/camilamaia/scanapi/issues/66.
After the refactor on the reporter templates, hide sensitive info from headers is not working. It shows the real data instead of `"<sensitive information>"`
Create a config file `.scanapi.yaml` with the content:
```
docs:
hide:
headers:
- Authorization
```
Run scanapi with this config file and set an Authorization header inside the api specification:
```
api:
base_url: ${BASE_URL}
headers:
Authorization: token123
```
The word `token123` will appear in the report, instead of `"<sensitive information>"`

Hiding sensitive info

---

README.md

At [PyPi page desccription](https://pypi.org/project/scanapi/0.0.15/) the image [scanapi-report-example.png](https://github.com/camilamaia/scanapi/blob/master/images/scanapi-report-example.png) is not loading
This happens because it is being used the relative path to link the image on README.md
How it is now:
```
<p align="center">
</p>
```
How it is should be:
```
<p align="center">
</p>
```
closes https://github.com/camilamaia/scanapi/issues/78

Fix report-example image not loading on PyPi

---

CONTRIBUTING.md
setup.py

Fix error when running scanapi v0.0.16
```    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: markdown.jinja
```
Also, it updates `CONTRIBUTING.md` with `PyPI Test` section
Closes https://github.com/camilamaia/scanapi/issues/84

Fix jinja2.exceptions.TemplateNotFound

---

CHANGELOG.md
pytest.ini
scanapi/evaluators/code_evaluator.py
scanapi/reporter.py
scanapi/settings.py
scanapi/tree/endpoint_node.py
scanapi/tree/request_node.py
scanapi/tree/root_node.py
tests/functional/step_defs/test_call_requests.py
tests/unit/factories.py
tests/unit/tree/test_api_tree.py
tests/unit/tree/test_endpoint_node.py

When creating requests without body It was setting body as  `{}` instead of None. The consequence of that is that it sends `content-length` as 2 in the headers, when it should not send `content-length` at all

Return body None when request has no body

---

CHANGELOG.md
scanapi/evaluators/string_evaluator.py
tests/unit/evaluators/test_string_evaluator.py

Before, If we defined a var containing an upper case letter, like:
```yaml
vars:
apiKey: abc123
```
and we tried to use it as `${apiKey}` it would raise the error:
```
ERROR:scanapi.evaluators.string_evaluator:'apiKey' environment variable not set or badly c
```
This PR fixes this problem. Fix #75

Fix when custom var has upper case

---

README.md

Update codecov badge links to use `/scanapi/scanapi` instead of `/camilamaia/scanapi`

Update codecov badge links

---

CHANGELOG.md
README.md
scanapi/__init__.py
scanapi/reporter.py
tests/unit/test_reporter.py

implement --template option

---

.circleci/config.yml
.github/workflows/lint.yml
CHANGELOG.md

Move black check from CircleCI to GitHub actions:
https://github.com/marketplace/actions/black-code-formatter
Closes #136

Move black check to github actions

---

CONTRIBUTING.md

Removed docker hub step from deploy. Now deploy on docker hub is done automated via [automated builds](https://docs.docker.com/docker-hub/builds/). 
We need to test it in the next release.

Removed docker hub step from deploy.

---

CHANGELOG.md
setup.py

- PATCH HTTP method - [#77](https://github.com/scanapi/scanapi/issues/77)
- Ability to have API spec in multiples files - [#125](https://github.com/scanapi/scanapi/issues/125)
- CLI `--config-path` option - [#128](https://github.com/scanapi/scanapi/issues/128)
- CLI `--template-path` option - [#126](https://github.com/scanapi/scanapi/pull/126)
- GitHub Action checking for missing changelog entry - [#134](https://github.com/scanapi/scanapi/pull/134)
- Make markdown report a bit better - [#96](https://github.com/scanapi/scanapi/issues/96)
- `base_url` keyword to `path` [#116](https://github.com/scanapi/scanapi/issues/116)
- `namespace` keyword to `name` [#116](https://github.com/scanapi/scanapi/issues/116)
- `method` keyword is not mandatory anymore for requests. Default is `get` …

Release v0.0.19

---

.github/workflows/publish-to-pypi.yml
CHANGELOG.md
CONTRIBUTING.md
pyproject.toml

Automated PyPI deploy with Github Actions
Reference: https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
Closes #36 
We can test it properly in the next release

Automated PyPI deploy with Github Actions

---

.circleci/config.yml

Use the official [rcmachado/changelog](https://hub.docker.com/r/rcmachado/changelog) docker image in CI - so we don't need to download the binary in every run.

Use rcmachado/changelog image for CI

---

CHANGELOG.md
scanapi/reporter.py
scanapi/templates/html.jinja
scanapi/templates/markdown.jinja

New HTML template using jinja. 🥳 
- Assets uploaded to S3 (@camilamaia)
The reason the CSS is inline is because we want to avoid adding useless dependencies to the project.
Closes #61 https://github.com/scanapi/scanapi/issues/57

New Html template

---

CHANGELOG.md
scanapi/settings.py
tests/unit/test_settings.py

Change default template to html. Closes #159

Change default template to html

---

CHANGELOG.md
scanapi/templates/html.jinja
scanapi/utils.py
tests/unit/test_utils.py

- Remove duplicated status code row from report
- Fix sensitive information render on report. It was not showing in the report because it was being interpreted as a html tag
Detailed explanation of each problem in their respective issues
👇 
Closes #181 
Closes #182

Fix sensitive information and duplicated row on report

---

CHANGELOG.md
scanapi/main.py
scanapi/reporter.py
scanapi/scan.py
scanapi/session.py
scanapi/template_render.py
scanapi/templates/html.jinja
scanapi/tree/request_node.py
scanapi/tree/testing_node.py
setup.py
tests/unit/test_reporter.py
tests/unit/test_session.py
tests/unit/test_template_render.py
tests/unit/tree/test_request_node.py
tests/unit/tree/test_testing_node.py

- Show a tests summary in the HTML report
- Show each test result in the html report
- Small refactor on Reporter
Current this is how it is rendered: https://github.com/scanapi/scanapi/blob/adr2/testing_reports/current.html
But we are still discussing better how we are going to present it #161 . We can improve it later in the next PRs.
Closes #169 
Closes #167

Add tests results to html report

---

CHANGELOG.md
setup.py

- Add new HTML template [#157](https://github.com/scanapi/scanapi/pull/157)
- Tests key [#152](https://github.com/scanapi/scanapi/pull/152)
- `-h` alias for `--help` option [#172](https://github.com/scanapi/scanapi/pull/172)
- Test results to report [#177](https://github.com/scanapi/scanapi/pull/177)
- Add test errors to the report [#187](https://github.com/scanapi/scanapi/pull/187)
- Hides sensitive info in URL [#185](https://github.com/scanapi/scanapi/pull/185)
- CLI options explanation [#189](https://github.com/scanapi/scanapi/pull/189)
- Unified keys validation in a single method [#151](https://github.com/scanapi/scanapi/pull/151)
- Default template to html [#173](https://github.com/scanapi/scanapi/pull/173)
- Project name color on html reporter to match ScanAPI brand …

Release v1.0.0

---

CHANGELOG.md
scanapi/templates/html.jinja

- Status icons are not vertically centred in the Report [#190]

Vertically centered status icons

---

CHANGELOG.md
pyproject.toml

- Status icons on report were not vertically centered [#195](https://github.com/scanapi/scanapi/pull/195)

Release v1.0.5

---

CHANGELOG.md
README.md
scanapi/scan.py
scanapi/tree/tree_keys.py
tests/data/api_invalid_path_include.yaml
tests/data/api_wrong_format_include.yaml
tests/data/jsonfile.json
tests/data/not_supported_format.txt
tests/data/scanapi.yaml
tests/unit/test_config_loader.py
tests/unit/test_scan.py

In #209 it was suggested to remove the top-level `api` key, this PR removes that but it does not deal with the possibility of it being there. Since for the previous PRs we let things ride regarding backwards compatibility I wonder if it's still necessary for this PR.
Closes #209

Remove the `api` top-level key

---

CHANGELOG.md
scanapi/hide_utils.py
scanapi/reporter.py
tests/unit/test_hide_utils.py

* reporter.py: `project-name` -> `project_name`
* hide_utils.py: `hide-request` -> `hide_request`
* hide_utils.py: `hide-response` -> `hide_response`
closes #228

Updated naming convetions to use underscore

---

.pre-commit-config.yaml
CONTRIBUTING.md
poetry.lock
pyproject.toml

`pre-commit` was not being installed. When I try to add it, I faced this error:
```shell
$ poetry add -D pre-commit
Using version ^2.6.0 for pre-commit
Updating dependencies
Resolving dependencies... (0.0s)
[SolverProblemError]
The current project's Python requirement (^3.6) is not compatible with some of the required packages Python requirement:
- pre-commit requires Python >=3.6.1
Because no versions of pre-commit match >2.6.0,<3.0.0
and pre-commit (2.6.0) requires Python >=3.6.1, pre-commit is forbidden.
So, because scanapi depends on pre-commit (^2.6.0), version solving failed.
```
for this reason, I increase the python version from 3.6 to 3.7 too

Add pre-commit to poetry

---

CHANGELOG.md
scanapi/hide_utils.py
tests/unit/test_hide_utils.py

When trying to hide body sensitive information:
```yaml
report:
hide_request:
headers:
- Authorization
body:
- get_token
```
the user is facing this error:
`a bytes-like object is required, not 'str'`
This PR fixes it. Closes #235

Fix hide body sensitive info

---

CHANGELOG.md
README.md

Readme clean up. Move documentation from README.md to the website
Closes https://github.com/scanapi/scanapi/issues/227

Readme clean up

---

scanapi/reporter.py
scanapi/templates/report.html
tests/unit/test_reporter.py

Rename html.jinja to report.html.
We only have one report type now. Does not make sense to call it `html.jinja`.

Rename html.jinja to report.html

---

.github/workflows/publish-to-pypi.yml
.github/workflows/publish-to-test-pypi.yml
pyproject.toml

Update poetry-publish action, that fixes authentication problem when using repository params.
https://github.com/JRubics/poetry-publish/releases/tag/v1.2
Closes #249

Fix publish to Test PyPI

---

CHANGELOG.md
poetry.lock
pyproject.toml
scanapi/__main__.py
scanapi/config_loader.py
scanapi/scan.py
scanapi/settings.py
tests/unit/test_main.py
tests/unit/test_scan.py
tests/unit/test_settings.py

Initial support for a different configuration filename and global configuration.
Created on top of: https://github.com/scanapi/scanapi/pull/225
closes #203
closes #131

feat: Add local/global configuration support

---

CHANGELOG.md
pyproject.toml

- JSON response is now properly rendered, instead of plain text. [#213](https://github.com/scanapi/scanapi/pull/213)
- The report page now has a favicon. [#223](https://github.com/scanapi/scanapi/pull/223)
- Bandit security audit tool. [#219](https://github.com/scanapi/scanapi/pull/219)
- Add Sphinx auto-documentation. [#230](https://github.com/scanapi/scanapi/pull/230)
- Add workflow to package/publish to Test PyPi. [#239](https://github.com/scanapi/scanapi/pull/239)
- Renamed `api.(yaml|json)` to `scanapi.yaml`. [#222](https://github.com/scanapi/scanapi/issues/20://github.com/scanapi/scanapi/pull/222)
- Remove top-level `api` key in `scanapi.yaml`. [#231](https://github.com/scanapi/scanapi/pull/231)
- Renamed `project-name`, `hide-request` and `hide-response` to use underscore. …

Release v2.0.0

---

.github/actions/black/Dockerfile
.github/actions/black/entrypoint.sh
.github/workflows/lint.yml

`lgeiger/black-action` github action does not permit to set a specific version for Black. The action always install it using `pip install black`. See the code [here](https://github.com/lgeiger/black-action/blob/master/Dockerfile#L12)
For our project we fixed the version on [19.10b0](https://github.com/scanapi/scanapi/blob/f1a3b20892a3356f07a8688a63ee51c0c7bb3291/pyproject.toml#L33)
Because of that, our checks started failing. 
https://github.com/scanapi/scanapi/pull/272/checks?check_run_id=1109422609
We could create a PR to implement this in the action, the same way we did for the `JRubics/poetry-publish` action, but the repository seems not having updates since last year.
Since the code is pretty simple, I decided to implement it inside our project.
closes …

Implemented black action

---

CHANGELOG.md
pyproject.toml
scanapi/tree/request_node.py
tests/unit/tree/test_request_node.py

On requests that have no `body`, ScanAPI is sending body as `{}` and Content-Length equals 2. The body should be None and the Content-Length should be 0.
Closes https://github.com/scanapi/scanapi/issues/262

Set no `body` as None instead of `{}`

---

CHANGELOG.md
poetry.lock
pyproject.toml

I moved the bandit dependency to the **dev** section in the `pyproject.toml` file and recreated the `poetry.lock` file, according to issue #269.

Moved bandit to dev section

---

poetry.lock
pyproject.toml

- Context: the `pytest` settings moved from `pytest.ini` to `pyproject.toml` in the PR https://github.com/scanapi/scanapi/pull/283 are not actually being used because we are using an older `pytest` version which doesn't support `pyproject` (by running `make test` you can see the verbose mode is not activated).
- This PR fix it by upgrading `pytest` to version `6.1.0`.
- Related to the issue https://github.com/scanapi/scanapi/issues/276.

Upgrade pytest version to 6.1.0

---

CHANGELOG.md
tests/unit/evaluators/test_spec_evaluator.py

increased spec_evaluator test coverage

---

CHANGELOG.md
pyproject.toml

- Add a `delay` key option to perform a delay between each request. [#266](https://github.com/scanapi/scanapi/issues/266)
- Changed relative path to show absolute path to the report in CLI. [#277](https://github.com/scanapi/scanapi/pull/277)
- Considering `-` (dash) in variable names. [#281](https://github.com/scanapi/scanapi/pull/281)
- Moved bandit to dev section [#285](https://github.com/scanapi/scanapi/pull/285)
- Increased Test coverage for `/scanapi/evaluators/spec_evaluator.py` [#291](https://github.com/scanapi/scanapi/pull/291)
- When there is no `body` specified, sending it as `None` instead of `{}`. [#280](https://github.com/scanapi/scanapi/pull/280)
- Removed unused imports. [#294](https://github.com/scanapi/scanapi/pull/294)

Release v2.1.0

---

CHANGELOG.md
scanapi/templates/report.html

Hi everyone! I just implemented an solution for this issue: https://github.com/scanapi/scanapi/issues/260. The feature is already working, you just need to add the endpoint list index to the url and it's gonna open the page in the correct endpoint, e.g. url: ``Documents/scan-api/scanapi/scanapi-report.html#endpoint_4``.
I think that we have 2 more things to implement here: 
- would be nice to numerate the endpoints in the list, that way would be easy to the user to know the endpoint index.
- would be great to have an "share" button in the endpoint view, so the user can click on it an copy the custom url to clipboard.
I noticed another thing when editing the template HTML file, maybe would be more acessible if we start using an ``<ul>`` tag for the endpoints wrapper and ``<li>`` tags for …

Add anchor link for each request in the report to make it easily shareable

---

CHANGELOG.md
scanapi/hide_utils.py
tests/unit/test_hide_utils.py

Add a report configuration option to hide sensitive information in the url query params.
Solves #304.

Hide sensitive information in the URL Query Params

---

.pre-commit-config.yaml
CHANGELOG.md

Just updating the black version on pre-commit file to avoid the bug related to black issue  [#1288](https://github.com/psf/black/issues/1288).

solves #345 updating black version on pre-commig  configs.

---

.pre-commit-config.yaml
tests/unit/evaluators/test_code_evaluator.py
tests/unit/evaluators/test_spec_evaluator.py
tests/unit/evaluators/test_string_evaluator.py
tests/unit/tree/test_endpoint_node.py

- tests/unit/evaluators/test_code_evaluator.py
- tests/unit/evaluators/test_spec_evaluator.py
- tests/unit/evaluators/test_string_evaluator.py
- tests/unit/tree/test_endpoint_node.py
Related to #339

Refactor on tests to use pytest-it

---

CHANGELOG.md
Dockerfile
pyproject.toml

- Hide sensitive information in the URL Query Params [#304](https://github.com/scanapi/scanapi/pull/325)
- Anchor link for each request in the report to make it easily shareable. [#317](https://github.com/scanapi/scanapi/pull/317)
- Support to HTTP methods HEAD and OPTIONS [#350](https://github.com/scanapi/scanapi/pull/350)
- The `retry` key under requests to setup retry for requests. [#298](https://github.com/scanapi/scanapi/issues/298)
- Curl command [#330](https://github.com/scanapi/scanapi/pull/330)
- Render body according to its request content type [#331](https://github.com/scanapi/scanapi/pull/331)

Release v2.2.0

---

CHANGELOG.md
scanapi/hide_utils.py
tests/unit/test_hide_utils.py

Fixed hide_response body (#370)

---

CHANGELOG.md
Dockerfile
pyproject.toml

- `--version` command to return current scanapi version. [#372](https://github.com/scanapi/scanapi/pull/372)
- hide_response body. [#375](https://github.com/scanapi/scanapi/pull/375)

Release v2.3.0

---

CHANGELOG.md
scanapi/hide_utils.py
tests/unit/test_hide_utils.py

Fix error making request when request has no body and there is a `report::hide_request::body` configuration.
Closes #392 
Bug fix
Closes 392

Fix making request that has no body and there is a hide_request::body config

---

CHANGELOG.md
scanapi/templates/report.html
scanapi/tree/request_node.py
tests/unit/tree/request_node/test_run.py

Show request names in the report.
Requests for different purposes with the same paths.
Feature
Closes #354

Added request name to results variable passed to report (#354)

---

scanapi/template_render.py

* updated Environment(loader=loader) -> Environment(loader=loader, autoescape=True)
Closes: https://github.com/scanapi/scanapi/issues/401
Enable autoescape in `scanapi/template_render,py::render(template_path, context, is_external=False)` 
Using Jinja2 templates without autoescaping enabled leaves application vulnerable to [XSS attacks](https://owasp.org/www-project-top-ten/2017/A72017-Cross-SiteScripting_(XSS).
Bug Fix
Closes 401

Enable autoescape in template_render

---

scanapi/config_loader.py
scanapi/reporter.py
scanapi/scan.py
scanapi/session.py
scanapi/settings.py
scanapi/template_render.py
scanapi/test_status.py
scanapi/utils.py

Fix: No whitespaces allowed surrounding docstring text. We should avoid spaces at the beginning and at the end of a docstring.
There are 25 occurrences of this issue in the repository.
See all occurrences on DeepSource &rarr; [deepsource.io/gh/scanapi/scanapi/issue/FLK-D210/occurrences/](https://deepsource.io/gh/scanapi/scanapi/issue/FLK-D210/occurrences/)
Solve deepsource issues
Fix
Closes #412

Fix: No whitespaces allowed surrounding docstring text

---

scanapi/tree/testing_node.py

The method doesn&#x27;t use its bound instance. Decorate this method with `@staticmethod` decorator, so that Python does not have to instantiate a bound method for every instance of this class thereby saving memory and computation. Read more about staticmethods [here](https://docs.python.org/3/library/functions.html#staticmethod).
There are 177 occurrences of this issue in the repository.
See all occurrences on DeepSource &rarr; [deepsource.io/gh/scanapi/scanapi/issue/PYL-R0201/occurrences/](https://deepsource.io/gh/scanapi/scanapi/issue/PYL-R0201/occurrences/)
Fix deepsource issues
Fix
Closes #414

Fix: No use of self PYL-R0201

---

.github/workflows/lint.yml
.github/workflows/run-examples.yml
poetry.lock
pyproject.toml

- there was an update in [curlif2](https://pypi.org/project/curlify2/#history) library for `1.0.1 version`.
- the requests library has been update for 2.26
- poetry accept python `>=3.6.2,<4.0.0 `

updating requests and curlify2 library

---

.github/workflows/publish-to-test-pypi.yml
CODE_OF_CONDUCT.md
README.md

Rename master to main on ci
https://github.com/github/renaming
Refactor
Closes #214

Rename master to main on ci

---

scanapi/tree/endpoint_node.py
scanapi/utils.py

Refactor on `_validate` method of EndpointNode. The method `validate_keys` has no return. `return` is used here to avoid calling `validate_keys` again.
Avoid confusion.
Refactor
Closes #423

Refactor on _validate method of EndpointNode

---

scanapi/__main__.py
scanapi/config_loader.py
scanapi/exit_code.py

These docstrings fits in a single line according to PEP8.
Reference: https://deepsource.io/gh/scanapi/scanapi/issue/FLK-D200/occurrences
Solve DeepSource issues.
Fix
Closes #411

Fix: Docstrings converted to single-line

---

CHANGELOG.md
scanapi/templates/report.html

- Use break-all css in the right columns of the table to prevent overflow,
- Update the Changelog
Fix for issue https://github.com/scanapi/scanapi/issues/409
in some html tables when there is long data, the data gets out of the table
Bug Fix
Closes 409

Fix: Break lines in column to prevent overflow

---

scanapi/exit_code.py

Updated doc strung to fit on one line with quotes
Fixes (FLK-D200) One-line docstring should fit on one line with quotes #454
Bug Fix
Closes https://github.com/scanapi/scanapi/issues/454

Updated doc strung to fit on one line with quotes

---

Makefile

Make "make change-version" useful again by keeping the current release version, and adding a human readable and PEP440 compliant timestamp to it.
Also fixed `PHONY`.
Closes https://github.com/scanapi/scanapi/issues/464

make change-version: create a readable PEP440-compatible dev version

---

scanapi/evaluators/code_evaluator.py
scanapi/evaluators/spec_evaluator.py
scanapi/evaluators/string_evaluator.py
scanapi/tree/endpoint_node.py
scanapi/tree/request_node.py
scanapi/tree/testing_node.py
tests/unit/evaluators/test_code_evaluator.py
tests/unit/evaluators/test_spec_evaluator.py
tests/unit/evaluators/test_string_evaluator.py
tests/unit/tree/endpoint_node/test_validate.py
tests/unit/tree/request_node/test_validate.py

Implements #436 
Since vars() is a builtin keyword. It's generally an anti-pattern to redefine builtin functions.

replace 'vars' with 'spec_vars' (close #436)

---

scanapi/config_loader.py
scanapi/errors.py
tests/data/api_non_scalar_include.yaml
tests/unit/test_config_loader.py

The typing already present in the `scanapi.config_loader` module raises `mypy` errors.  For #456 to work these erros need to be fixed.
The `mypy` errors were actually helpful to identify a potential source of errors in parsing of config files, which has also been fixed.
Mypy will presumable be part of the CI, so all type annotations have to be correct.
Since #456 has not been merged yet one needs to either manually install `mypy`, or rebase this branch onto the branch from #456:
```
git rebase --onto=add-mypy main
```
then 
```
make mypy
```
undo rebase
```
git rebase --onto=main add-mypy
git reset origin/fix/config-loader-typing
```
Fix wrong type annotation.
Closes #457

Fix typing in `config_loader`

---

Makefile

format version identifiers according to PEP 440, without dots after dev numbers. https://www.python.org/dev/peps/pep-0440/#public-version-identifiers
Poetry throw invalid version during build.
Fix
Closes #467

Invalid version in poetry build (#467)

---

scanapi/evaluators/code_evaluator.py

``assert`` should not be used in runtime code (it can be disabled), and besides that the new code is simpler.
Questionable is the use of ``None``, since the docs say something else (``None`` not a string is), and an empty string would be better if the callers survive the type change (truthiness would not change).
And finally, why not *always* return the code, or not at all (the caller just gave us the code, so it has it anyway).
Closes #480

code_evaluator: fix runtime usage of 'assert'

---

CHANGELOG.md
scanapi/templates/report.html

update report summary test location
update report classes following BEMCSS pattern
close unclosed html tags
[478](https://github.com/scanapi/scanapi/issues/478)
Feature
Closes #478

update report summary test location

---

scanapi/evaluators/string_evaluator.py

Removed unuseful lines. `matches` variable is a callable_iterator object, so it will never be null. We can remove the check since when there is no match with the pattern, it will not go into the loop.
Refactor
Closes #488

Remove if not matches: from StringEvaluator

---

tests/unit/tree/endpoint_node/test_repr.py

This pull request add a unit test for __repr__ for the Endpoint class inside test_repr.py
#484 
Unit test
Closes #484

add unit test for _repr__ method for EndpointNode class  #484

---

tests/unit/tree/request_node/test_repr.py

This pull request adds unit tests for the method `__repr__` of RequestNode class
Add unit tests and closes issue #485 
Unit tests
Closes #485

test: add unit test for method '__repr__' of RequestNode class

---

CHANGELOG.md
Dockerfile
pyproject.toml

- Summary tests location to the top of the report [#479](https://github.com/scanapi/scanapi/pull/479)
- Header table gets broken. [#432](https://github.com/scanapi/scanapi/pull/432)

Release v2.6.0

---

CHANGELOG.md
scanapi/__main__.py
scanapi/reporter.py
scanapi/scan.py
scanapi/settings.py
tests/unit/test_main.py
tests/unit/test_scan.py
tests/unit/test_settings.py

I added a new option to open the report result on a browser.
Closes #465
It is a new feature
Closes #465

Add a --browse option in CLI

---

poetry.lock
pyproject.toml
scanapi/config_loader.py

The minimal version for `types-PyYAML` in `pyproject.toml` was upgraded from `^5.4.3` to `^5.4.6`.
Things done:
- Manually edit `pyproject.toml`
- Run `poetry lock --no-update`
- Remove obsolete comments in `config_loader.py`
Version 5.4.6 contains a fix for wrong type annotations. The fix
and additional type annotations were added in this PR:
https://github.com/python/typeshed/pull/5828
With an older version of `typtes-PyYAML`:
```
$ poetry show types-pyyaml
name         : types-pyyaml
version      : 5.4.5
description  : Typing stubs for PyYAML
$ mypy scanapi
scanapi/config_loader.py:59: error: Argument 2 to "add_constructor" has incompatible type "Callable[[scanapi.config_loader.Loader, Node], Any]"; expected "Callable[[yaml.loader.Loader, Node], Any]"  [arg-type] …
```

Upgrade types-PyYAML from ^5.4.3 to ^5.4.6

---

.github/workflows/lint.yml
.github/workflows/run-examples.yml

Ignore python minors in setup-python and bump setup-python version
#511
Bug fix
Closes #511

fix: ignore python minors in setup-python and bump its version

---

scanapi/evaluators/spec_evaluator.py

Fix typo in spec_evaluator.py
#525 
Code documentation fix.
Closes #525

fix typo in spec_evaluator.py

---

CHANGELOG.md
scanapi/templates/report.html

UI change:
1. add Gotham Font Family;
2. Variables CSS with colors;
2.1. Update red color to use: #f14668;
2.2. Update green color to use: #48c78e;
3. Add visual wrapper to following areas: request content, request response and request test;
4. New endpoint status UI;
Following recent discussions on #161 we decide to implement new details to help users on visualize related request data.
Feature
#161

Adr2/update report html UI

---

CHANGELOG.md
Dockerfile
pyproject.toml

- Implement new details to help users on visualize related request data. [#506](https://github.com/scanapi/scanapi/pull/506)
- Fix the `--browser` flag not working on macOS [#504](https://github.com/scanapi/scanapi/pull/504)
- Error on running ScanAPI. `ImportError: cannot import name 'soft_unicode' from 'markupsafe'` [#534](https://github.com/scanapi/scanapi/pull/534)

Release v2.6.1

---

.github/workflows/run-examples.yml
README.md

Enable run examples action to run on pushes to the main branch. Previously, it was only running in the PRs.
Added status badge for showing if the examples on main branch are running properly.
closes #491
Improves visibility of examples status
Feature
Closes #491

Run examples on push

---

CHANGELOG.md
Dockerfile
pyproject.toml

- Drops support for Python 3.6 since its EOL was reached out in December last year [549](https://github.com/scanapi/scanapi/pull/549)

Release v2.7.0

---

.pre-commit-config.yaml
CHANGELOG.md
scanapi/tree/request_node.py
tests/unit/tree/request_node/test_full_path_url.py

Custom variable will be evaluated when defined in the path
#508
Bug fix
Closes #508

fix: custom variable evaluated when defined on the path (#508)

---

CHANGELOG.md
Dockerfile
pyproject.toml

- Custom variable evaluated when defined on the path [#508](https://github.com/scanapi/scanapi/issues/508)
- Add missing `--insecure` flag to cURL command on report based on request options [#555](https://github.com/scanapi/scanapi/pull/555)

Release v2.8.1

---

CHANGELOG.md
scanapi/templates/report.html

Fix the issue linked + a bit of cleanup of the code around
Fix #551
bugfix
Closes #551

fix: content field didn't render properly on Chrome

---

CHANGELOG.md
scanapi/templates/report.html

Cleanup code linked to Chrome fix, turns out `.textContent` is all we need.
Tested on macOS on Safari, Chrome & Firefox.

refactor(report): cleanup chrome fix (#551)

---

CHANGELOG.md
poetry.lock
pyproject.toml
scanapi/tree/endpoint_node.py
scanapi/tree/request_node.py
scanapi/utils.py
tests/unit/test_utils.py
tests/unit/tree/request_node/test_run.py

Change requests to httpx
#208
Feature
Closes #208

feat: change requests to httpx

---

CHANGELOG.md
Dockerfile
pyproject.toml

- Change requests to httpx. [#208](https://github.com/scanapi/scanapi/issues/208)
- Drops support for Python 3.7 and Python 3.8 since their EOL were reached out already [678](https://github.com/scanapi/scanapi/pull/678)

Release v2.10.0

---

.github/workflows/pytest-and-codecov.yml
.github/workflows/run-examples.yml
tests/unit/tree/request_node/test_run.py

- Upgrade codecov action version to v5
- Adds explicit permissions to the Pytest and Codecov workflow, to make it more secure
- Fix `httpx.ConnectTimeout` on tests. The session was not being mocked properly.
Pipeline broken.
Workflow run example: https://github.com/scanapi/scanapi/actions/runs/15777341084/job/44479954817?pr=725
Fix of a pipeline
Closes #726

ci: upgrade codecov action

---

.github/workflows/pytest-and-codecov.yml

This PR improves the GitHub Actions workflow `pytest-and-codecov` by:
- Skip Codecov upload on forks to avoid token access errors
- Add coverage threshold check on forks to fail if coverage drops below 98%
- Keep Codecov upload and normal checks on main repository
Forked repositories do not have access to the CODECOV_TOKEN, causing the Codecov upload step to fail. This change prevents those errors by skipping the upload on forks while still ensuring coverage quality via a threshold check.
For reference, see the failing run here:
https://github.com/scanapi/scanapi/actions/runs/15825517892/job/44604576216?pr=725
Workflow / CI Improvement
Closes #739

ci: adapt pytest-and-codecov to handle forks

---

.github/workflows/first-interaction.yml
.github/workflows/lint.yml
.github/workflows/publish-to-production.yml
.github/workflows/publish-to-test-pypi.yml
.github/workflows/run-examples.yml

This PR adds explicit `permissions` to all GitHub Actions workflows to restrict their default access levels. By default, workflows run with broad permissions, which can pose security risks—especially in public repositories. Setting explicit permissions follows GitHub’s recommended best practices and helps limit the potential impact of compromised workflows.
GitHub recommends setting explicit permissions for workflows to avoid unnecessary access to sensitive scopes such as `contents: write`. Without this, workflows may have more access than needed, which is a potential security vulnerability. This change proactively improves the CI/CD security posture of the project.
There is no related issue because this is a security hardening improvement.
Security fix / CI hardening
There is no issue …

fix(ci): add explicit permissions to workflows

---

.github/dependabot.yml

chore(dependabot): add semi-monthly version updates w/ 10d cooldown
- pip: 1st & 15th at 09:00 America/Sao_Paulo, cooldown 10 days, prefix `chore(deps)`
- GitHub Actions: 1st & 15th at 09:00 America/Sao_Paulo, cooldown 10 days, prefix `ci(deps)`
- Security updates (pip & actions): enable via Settings → Code security and analysis
→ Dependabot alerts + Dependabot security updates (run continuously, bypass cooldown)
- Set PR limit to 5 and add standard labels
This aligns Dependabot with ScanAPI’s release cadence: fast CVE response without noise from fresh releases, and predictable 1st/15th update windows.
Reduce dependabot[bot] commit noise and make the commit history readable and meaningful releases. #799 
chore/configuration change: updating Dependabot scheduling, cooldowns, commit …

chore(dependabot): add semi-monthly version updates w/ 10d cooldown

---

.github/workflows/publish-to-test-pypi.yml

ci: prevent build-n-publish-test-pypi job from running on forks
